package test

import (
	"testing"
	"gopkg.in/h2non/gock.v1"
	"github.com/nbio/st"
)

func TestSearchProductRequest_Ok(t *testing.T)  {
	testRequest("hotelsearch_by_hotellist_response_example.xml")
	defer gock.Off()

	data, err := acApi.HotelSearchRequest("","","","","",
		0, 0, 0, 0, 0, 0, 0,0,0,
		0,0,0.00,0.00,nil,nil)
	er := getCustomErrorType()
	st.Expect(t, err, er)
	st.Expect(t, data.Language, "ru")
	st.Expect(t, data.ArrivalDate, "17.08.2017")
	st.Expect(t, data.DepartureDate, "18.08.2017")
	st.Expect(t, data.NumberOfGuests, 1)
	st.Expect(t, len(data.DestinationList.Items), 4)
	st.Expect(t, data.DestinationList.Items[0].Code, 800300)
	st.Expect(t, data.DestinationList.Items[0].Name, "Аквариум Отель")
	st.Expect(t, data.DestinationList.Items[0].DestinationType.Code, 3)
	st.Expect(t, data.DestinationList.Items[0].DestinationType.Name, "Отель")
	st.Expect(t, data.DestinationList.Items[0].ObjType.Code, 9500001)
	st.Expect(t, data.DestinationList.Items[0].ObjType.Name, " Hе имеет значения")
	st.Expect(t, data.DestinationList.Items[0].HotelType.Code, 2)
	st.Expect(t, data.DestinationList.Items[0].HotelType.Name, "Гостиница")
	st.Expect(t, data.DestinationList.Items[0].Position.Latitude, "55.828133")
	st.Expect(t, data.DestinationList.Items[0].Position.Longitude, "37.389736")
	st.Expect(t, data.DestinationList.Items[0].Position.OptimalGmapZoom, 15)
	st.Expect(t, len(data.AvailableHotelsList.Items), 3)
	st.Expect(t, data.AvailableHotelsList.Items[0].Code, 800300)
	st.Expect(t, data.AvailableHotelsList.Items[0].Name, "Аквариум Отель")
	st.Expect(t, data.AvailableHotelsList.Items[0].Zip, "143402")
	st.Expect(t, data.AvailableHotelsList.Items[0].Address, "Международная улица, 20")
	st.Expect(t, data.AvailableHotelsList.Items[0].CityCentre, "Центр города - 21 км")
	st.Expect(t, data.AvailableHotelsList.Items[0].Airport, "Шереметьево - 22 км, Внуково - 31 км, Остафьево - 44 км, Быково - 59 км, Домодедово - 66 км")
	st.Expect(t, data.AvailableHotelsList.Items[0].RailwayStation, "Белорусский - 31 км")
	st.Expect(t, data.AvailableHotelsList.Items[0].Underground, "Мякинино - Арбатско-Покровская линия - 0,5 км")
	st.Expect(t, data.AvailableHotelsList.Items[0].Description, "Международный Выставочный Центр Крокус Экспо - 0,53 км")
	st.Expect(t, data.AvailableHotelsList.Items[0].Url, "http://images.acase.ru/hotels_images/800300_00.jpg")
	st.Expect(t, data.AvailableHotelsList.Items[0].Ref, "aquarium-hotel")
	st.Expect(t, data.AvailableHotelsList.Items[0].DistanceToDestination, 0)
	st.Expect(t, data.AvailableHotelsList.Items[0].DefaultCheckOutTime, "12:00")
	st.Expect(t, data.AvailableHotelsList.Items[0].DefaultCheckInTime, "14:00")
	st.Expect(t, data.AvailableHotelsList.Items[0].ObjType.Code, 2)
	st.Expect(t, data.AvailableHotelsList.Items[0].ObjType.Name, "Гостиница")
	st.Expect(t, data.AvailableHotelsList.Items[0].City.Code, 2)
	st.Expect(t, data.AvailableHotelsList.Items[0].City.Name, "Москва")
	st.Expect(t, data.AvailableHotelsList.Items[0].City.Ref, "moscow")
	st.Expect(t, data.AvailableHotelsList.Items[0].City.Position.Latitude, "55.755773")
	st.Expect(t, data.AvailableHotelsList.Items[0].City.Position.Longitude, "37.617815")
	st.Expect(t, data.AvailableHotelsList.Items[0].AdmUnit1.Code, 1)
	st.Expect(t, data.AvailableHotelsList.Items[0].AdmUnit1.Name, "Не определено")
	st.Expect(t, data.AvailableHotelsList.Items[0].AdmUnit2.Code, 1)
	st.Expect(t, data.AvailableHotelsList.Items[0].AdmUnit2.Name, " Не определено")
	st.Expect(t, data.AvailableHotelsList.Items[0].TypeOfPlace.Code, 2)
	st.Expect(t, data.AvailableHotelsList.Items[0].TypeOfPlace.Name, "Город")
	st.Expect(t, data.AvailableHotelsList.Items[0].Country.Code, 9)
	st.Expect(t, data.AvailableHotelsList.Items[0].Country.Name, "Россия")
	st.Expect(t, data.AvailableHotelsList.Items[0].Country.Ref, "russia")
	st.Expect(t, data.AvailableHotelsList.Items[0].Country.Position.Latitude, "57.5158")
	st.Expect(t, data.AvailableHotelsList.Items[0].Country.Position.Longitude, "82.6172")
	st.Expect(t, data.AvailableHotelsList.Items[0].Position.Latitude, "55.828133")
	st.Expect(t, data.AvailableHotelsList.Items[0].Position.Longitude, "37.389736")
	st.Expect(t, data.AvailableHotelsList.Items[0].Rating.Code, 99)
	st.Expect(t, data.AvailableHotelsList.Items[0].Rating.Name, "-")
	st.Expect(t, data.AvailableHotelsList.Items[0].Stars.Code, 3)
	st.Expect(t, data.AvailableHotelsList.Items[0].Stars.Name, "Уровень 3 из 5")
	st.Expect(t, data.AvailableHotelsList.Items[0].Stars.Value, "3")
	st.Expect(t, data.AvailableHotelsList.Items[0].Stars.Url, "http://images.acase.ru/signs_images/Level 3 grey.svg")
	st.Expect(t, data.AvailableHotelsList.Items[0].Stars.OfficialCertificate.Code, 2)
	st.Expect(t, data.AvailableHotelsList.Items[0].Stars.OfficialCertificate.Name, "Государственный")
	st.Expect(t, data.AvailableHotelsList.Items[0].Stars.OfficialCertificate.Certificate.Code, 3)
	st.Expect(t, data.AvailableHotelsList.Items[0].Stars.OfficialCertificate.Certificate.Name, "3 звезды")
	st.Expect(t, data.AvailableHotelsList.Items[0].Stars.OfficialCertificate.Certificate.Url, "http://images.acase.ru/signs_images/three_stars_hotel.gif")
	st.Expect(t, data.AvailableHotelsList.Items[0].Stars.OfficialCertificate.Certificate.ValidBefore, "22.06.2019")
	st.Expect(t, len(data.AvailableHotelsList.Items[0].Amenities.Amenity), 0)
	st.Expect(t, data.AvailableHotelsList.Items[0].Currency.Code, 2)
	st.Expect(t, data.AvailableHotelsList.Items[0].Currency.Name, "RUB")
	st.Expect(t, len(data.AvailableHotelsList.Items[0].HotelOfferList.Items), 4)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].Code, 900460)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].NumberOfGuests, 1)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].NumberOfExtraBedAdult, 0)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].NumberOfExtraBedChild, 0)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].NumberOfExtraBedInfant, 0)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].IsHourRate, 2)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].MaxHours, 0)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].TotalPrice, 2980.00)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].VATIncludedInPrice, 454.58)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].FullVATInPrice, 1)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].TravelAgencyCommission, 298.00)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].RoomCode, 900250)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].RoomName, "Стандартный номер (вид на павильон)")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].RateCode, 900092)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].RateName, "")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].RateDescription, "")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].RateGroupCode, 2)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].RateGroupName, "Агенты УК")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].DeadlineDate, "16.08.2017")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].DeadlineTimeLoc, "16.08.2017 13:00")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].DeadlineTimeSys, "16.08.2017 13:00")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].DeadlineTimeUTC, "16.08.2017 10:00")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].PenaltySize, 2682.00)
	st.Expect(t, len(data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].SpecialOfferList.Items), 1)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].SpecialOfferList.Items[0].SpecialOfferType.Code, 0)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].SpecialOfferList.Items[0].SpecialOfferType.Id, 0)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].MealIncludedInPrice.Code, 3)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].MealIncludedInPrice.Name, "Завтрак Шведский стол")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].Availability.Code, 2)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].Availability.Name, "Свободная продажа")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].Availability.Allotment.Code, "9500001+1477869+9500001+2")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].Availability.Allotment.Name, "")
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].Availability.Allotment.Rooms, 5)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].WhereToPay.Code, 3)
	st.Expect(t, data.AvailableHotelsList.Items[0].HotelOfferList.Items[0].WhereToPay.Name, "Оплата ООО АКАДЕМСЕРВИС согласно договору")
	st.Expect(t, len(data.NoContractAvailableHotelsList.Items), 0)
	st.Expect(t, len(data.AlternativeHotelsList.Items), 0)
	st.Expect(t, len(data.NoContractAlternativeHotelsList.Items), 0)
}

func TestHotelSearchRequest_Error(t *testing.T) {
	testRequest("hotelsearch_error_example.xml")
	defer gock.Off()

	_, err := acApi.HotelSearchRequest("","","","","",
		0, 0, 0, 0, 0, 0, 0,0,0,
		0,0,0.00,0.00,nil,nil)

	st.Expect(t, err.Code, "9998")
	st.Expect(t, err.Message, "Доступ запрещен !")
}

